services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.file.rule=Host(`file.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.file.entrypoints=websecure"
      - "traefik.http.routers.file.tls=true"
      - "traefik.http.services.file.loadbalancer.server.port=9001"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=https://${TRAEFIK_DOMAIN}:${TRAEFIK_PORT}
      - LDAP_ORGANISATION=${LDAP_ORG:-redinfra}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  mc-init:
    image: minio/mc
    depends_on:
      - minio
    container_name: minio-mc-init
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - LDAP_BASEDN=${LDAP_BASEDN}
      - MINIO_LDAP_BIND_USER=${MINIO_LDAP_BIND_USER}
      - MINIO_LDAP_BIND_PASSWORD=${MINIO_LDAP_BIND_PASSWORD}
    volumes:
      - ./integrations/minio_ldap.sh:/scripts/minio_ldap.sh
    entrypoint: >
      /bin/sh -c "/scripts/minio_ldap.sh"
    restart: "no"
    networks:
      - web


volumes:
  minio_data: {}

networks:
  web:
    external: true
