services:
  gitea:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    restart: always
    volumes:
      - gitea_data:/var/lib/gitea
      - gitea_config:/etc/gitea
      - ./integrations/gitea_ldap.sh:/scripts/gitea_ldap.sh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA_APP_NAME=Red Infra Gitea
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${GITEA_DB_PASS}
    ports:
      - "127.0.0.1:8022:22"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`git.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    depends_on:
      - gitea-db

  gitea-db:
    image: postgres:${GITEA_DB_VERSION:-latest}
    container_name: gitea-db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${GITEA_DB_PASS}
      - POSTGRES_DB=gitea
    networks:
      - web
    volumes:
      - gitea_postgresql_data:/var/lib/postgresql/data

volumes:
  gitea_postgresql_data: {} 
  gitea_data: {}
  gitea_config: {}

networks:
  web:
    external: true