services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "127.0.0.1:${TRAEFIK_PORT}:443"
    labels:
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.services.app.loadbalancer.server.port=80"
    volumes:
      - ./configs/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    external: true